# Based on gitlab node and html CI templates.

# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

test_async:
  script:
    - npm install
    - echo Must add tests!

pages:
  stage: deploy
  script:
    - npm install
    - mkdir build
    - ./node_modules/.bin/tsc
    - ./node_modules/.bin/browserify src/tower.js > build/bundle.js
    - rm build/tower.js
    - ./node_modules/.bin/pug src/ --out build/
    - ./node_modules/.bin/sass src/:build/
    - mv build public
  interruptible: true
  artifacts:
    paths:
      - public
    expire_in: 3 days
  only:
    - master
